---

- hosts: all
  become: true
  tasks:
  

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" 
 
  - name: install apche2 pakage
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"        

  - name: add php 
    apt:
      name: libapache2-mod-php    
    when: ansible_distribution == "Ubuntu"


    - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "Centos"

  - name: install httpd pakage
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "Centos"

  - name: add php
    dnf:
      name: php
    when: ansible_distribution == "Centos"


